### ISSUE TITLE
Prepare for SPV3.3.1

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#208]
- [x] #207 Remove mouse acceleration EXE-patch
- [ ] #205 Hash all files after installation/deployment to ensure they were extracted correctly
- [x] #197 Merge WindowStore/GamePass detection into master
- [ ] #204 Improve WS/GP detection feature
- [ ] #209 Delete bad player profiles

**Comment by BinToss** [comment]
Migrating to [Prepare for SPV3.3.1 project](https://github.com/HaloSPV3/HCE/projects/1)...

**Comment by BinToss** [comment]
Migration completed.
